@startuml
abstract class " public Data Interface"{

    void initializeDatabase(String filename)
    void createEntry()
    void readEntry()
    void updateEntry()
    void deleteEntry()
    void saveEntry()  

}
@enduml
